version: 2.1
jobs:
    build-and-test:
        working_directory: ~/countdown-generator
        docker:
            - {image: 'circleci/node:12.11.1'}
        steps:
            - checkout
            - {restore_cache: {keys: ['dependency-cache-{{ checksum "package-lock.json" }}', dependency-cache-]}}
            - {run: 'npm install'}
            - {save_cache: {paths: [~/countdown-generator/cache], key: dependency-cache}}
            - {run: 'npm test'}
workflows:
  version: 2
  master:
    jobs:
      - build-and-test